time="2024-05-21T19:30:38+03:00" level=info msg="document file with id 24fa1fc3-791e-4815-be5a-605445f73509 was saved\n" func="annotater/internal/bl/documentService.(*DocumentService).LoadDocument" file="/home/andrew/uni/PPO/src/internal/bl/documentService/documentService.go:70"
time="2024-05-21T19:30:38+03:00" level=info msg="document metadata with id 24fa1fc3-791e-4815-be5a-605445f73509 was saved\n" func="annotater/internal/bl/documentService.(*DocumentService).LoadDocument" file="/home/andrew/uni/PPO/src/internal/bl/documentService/documentService.go:77"
time="2024-05-21T19:30:38+03:00" level=error msg="error getting model response: Post \"http://0.0.0.0:5000/pred\": dial tcp 0.0.0.0:5000: connect: connection refused\n" func="annotater/internal/bl/NN/NNAdapter/NNmodelhandler.(*HttpModelHandler).GetModelResp" file="/home/andrew/uni/PPO/src/internal/bl/NN/NNAdapter/NNmodelhandler/NNmodelhandler.go:66"
time="2024-05-21T19:30:38+03:00" level=error msg="Error in svc - creating report : Error in creating report: Error in Checking document: error in getting predictions for document 24fa1fc3-791e-4815-be5a-605445f73509\nerror in getting NN response\nPost \"http://0.0.0.0:5000/pred\": dial tcp 0.0.0.0:5000: connect: connection refused" func="main.main.func2.1.(*Documenthandler).CreateReport.1" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/document/document.go:227"
time="2024-05-21T19:31:40+03:00" level=warning msg="unable to signIn with user login 2:wrong login\nitem not found\n\n" func="main.main.(*AuthHandler).SignIn.func5" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/auth/auth.go:86"
time="2024-05-21T19:31:51+03:00" level=error msg="error getting model response: Post \"http://0.0.0.0:5000/pred\": dial tcp 0.0.0.0:5000: connect: connection refused\n" func="annotater/internal/bl/NN/NNAdapter/NNmodelhandler.(*HttpModelHandler).GetModelResp" file="/home/andrew/uni/PPO/src/internal/bl/NN/NNAdapter/NNmodelhandler/NNmodelhandler.go:66"
time="2024-05-21T19:31:51+03:00" level=error msg="Error in svc - creating report : Error in creating report: Error in Checking document: error in getting predictions for document b07c66e1-617a-4188-be3d-a63a075630a9\nerror in getting NN response\nPost \"http://0.0.0.0:5000/pred\": dial tcp 0.0.0.0:5000: connect: connection refused" func="main.main.func2.1.(*Documenthandler).CreateReport.1" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/document/document.go:227"
time="2024-05-21T19:34:20+03:00" level=warning msg="unable to signIn with user login admin:wrong login\nitem not found\n\n" func="main.main.(*AuthHandler).SignIn.func5" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/auth/auth.go:86"
time="2024-05-21T19:35:48+03:00" level=warning msg="Error in adding anotattion svc with ID 12\n: ID of this markup already exists\n" func="main.main.func2.2.(*AnnotTypeHandler).AddAnnotType.1" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/annotType/annotType.go:85"
time="2024-05-21T19:37:27+03:00" level=error msg="error in adding anotattion svc  with creator id 1: Invalid filetype" func="main.main.func2.3.(*AnnotHandler).AddAnnot.1" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/annot/annot.go:98"
time="2024-05-21T19:38:36+03:00" level=error msg="Error in svc - saving metadata of a document: Error in updating document: failed to connect to `host=localhost user=andrew database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" func="main.main.func2.1.(*Documenthandler).CreateReport.1" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/document/document.go:227"
time="2024-05-21T19:39:03+03:00" level=warning msg="error in getting all anotattions svc: Error in getting anotattion type: failed to connect to `host=localhost user=andrew database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" func="main.main.func2.3.(*AnnotHandler).GetAllAnnots.5" file="/home/andrew/uni/PPO/src/internal/http-server/handlers/annot/annot.go:141"
time="2024-05-21T20:51:10+03:00" level=fatal msg="failed to connect to `host=localhost user=andrew database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" func=main.main file="/home/andrew/uni/PPO/src/internal/cmd/main.go:74"
time="2024-05-21T21:09:10+03:00" level=fatal msg="failed to connect to `host=localhost user=andrew database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" func=main.main file="/home/andrew/uni/PPO/src/internal/cmd/main.go:77"
time="2024-05-21T21:09:51+03:00" level=fatal msg="failed to connect to `host=localhost user=andrew database=postgres`: dial error (dial tcp 127.0.0.1:5432: connect: connection refused)" func=main.main file="/home/andrew/uni/PPO/src/internal/cmd/main.go:77"
